### ISSUE TITLE
Enlace a nuestro subsistema | Subsistema Almacenamiento 

### ISSUE THREAD

**Issue by AlbertFX91** [jorgeron/CensoEGC#14]
Buenas
A continuación os dejo el enlace a nuestro subsistema para que podais incluirlo en vuestra aplicación, para que los usuarios que quieran puedan llegar a nuestra página.

http://storage-egc1516.rhcloud.com/

Muchas gracias y un saludo

**Comment by jorgeron** [comment]
Se ha creado el botón solicitado
