### ISSUE TITLE
Recuento: Petición de enlace a nuestro subsistema

### ISSUE THREAD

**Issue by rafaeldrs** [jorgeron/CensoEGC#15]
Buenas,

Desde recuento, os hacemos la petición de que añadáis un botón en la interfaz de vuestro subsistema con el nombre de "Recuento" y un enlace a nuestro subsistema (https://recuento.herokuapp.com/). 

Muchas gracias y un saludo

**Comment by jorgeron** [comment]
Se ha creado el botón solicitado en la interfaz.
