### ISSUE TITLE
Internacionalización

### ISSUE THREAD

**Issue by susmarmar** [jorgeron/CensoEGC#6]
En el controlador CensusController.java se detectan capturas de excepciones sin internacionalizar.

**Comment by laugardel** [comment]
Incidencia Terminada: se han aplicado los cambios necesarios en los archivos .properties del proyecto, se ha desplegado la aplicación y se ha comprobado que los cambios se han efectuado correctamente.

**Comment by iheluani** [comment]
Incidencia verificada: Tras desplegar la aplicación y comprobar su correcto funcionamiento, doy por verificada la resolución de esta incidencia.
