### ISSUE TITLE
Error en la clase PopulateDatabase.xml

### ISSUE THREAD

**Issue by iheluani** [jorgeron/CensoEGC#7]
Nuestro equipo decidió subir la rama prueba_populate a la rama máster para que todos comenzáramos a realizar las mejoras sobre el proyecto modificado para poder probar las funcionalidades del mismo sin necesitar la integración con el resto de módulos.
Esto se logró creando entidades dentro de la clase PopulateDatabase.xml. No obstante, a la hora de hacer merge, intenté probar la funcionalidad del proyecto y no conseguía acceder a apartados donde antes, desde la rama prueba_populate sí podía acceder.
Abro esta incidencia dada la necesidad de resolver este problema.

**Comment by jorgeron** [comment]
El error estaba en la clase CensusController.java, ya que se habían perdido algunos datos de prueba al resolver un conflicto. Recuperados esos datos y subidos a la rama master.
